"""An extension to RadarData for loading RxData types and BEVE files generated by the RFSoC interface software, SoulHardware"""
module SoulExt

using SoulHardware
using RadarData
using FFTW: fftshift, fftfreq, fft!
using BEVE: BeveDeserializer, parse_value
using StaticArrays
using Geodesy: ECEF, ENU
using Dates

include("./rxdata.jl")
include("./ins.jl")

end # module
